/*
=============================================================================
INNOCEAN USA ADVERTISING INTELLIGENCE - ANALYTICAL VIEWS
=============================================================================
Script: 04_create_views.sql
Purpose: Create analytical views for reporting and semantic models
Created: January 2026
=============================================================================
*/

USE DATABASE INNOCEAN_INTELLIGENCE;
USE SCHEMA ANALYTICS;

-- ============================================================================
-- VIEW 1: CAMPAIGN 360 - Comprehensive campaign performance view
-- ============================================================================

CREATE OR REPLACE VIEW V_CAMPAIGN_360 AS
SELECT
    c.CAMPAIGN_ID,
    c.CAMPAIGN_NAME,
    c.CAMPAIGN_TYPE,
    c.CAMPAIGN_OBJECTIVE,
    c.START_DATE AS CAMPAIGN_START_DATE,
    c.END_DATE AS CAMPAIGN_END_DATE,
    DATEDIFF(DAY, c.START_DATE, COALESCE(c.END_DATE, CURRENT_DATE())) AS CAMPAIGN_DURATION_DAYS,
    c.STATUS AS CAMPAIGN_STATUS,
    cl.CLIENT_ID,
    cl.CLIENT_NAME,
    cl.INDUSTRY AS CLIENT_INDUSTRY,
    cl.CLIENT_SEGMENT,
    cl.RELATIONSHIP_TYPE,
    c.TOTAL_BUDGET,
    c.MEDIA_BUDGET,
    c.PRODUCTION_BUDGET,
    c.TARGET_AUDIENCE,
    c.TARGET_GEO,
    c.TARGET_IMPRESSIONS,
    c.TARGET_REACH,
    c.TARGET_FREQUENCY,
    c.TARGET_CTR,
    c.TARGET_CONVERSION_RATE,
    c.TARGET_ROAS,
    c.ACTUAL_IMPRESSIONS,
    c.ACTUAL_REACH,
    c.ACTUAL_CLICKS,
    c.ACTUAL_CONVERSIONS,
    c.ACTUAL_REVENUE,
    c.ACTUAL_ROAS,
    CASE WHEN c.TARGET_IMPRESSIONS > 0 THEN c.ACTUAL_IMPRESSIONS / c.TARGET_IMPRESSIONS ELSE NULL END AS IMPRESSION_DELIVERY_RATE,
    CASE WHEN c.ACTUAL_IMPRESSIONS > 0 THEN c.ACTUAL_CLICKS / c.ACTUAL_IMPRESSIONS ELSE NULL END AS ACTUAL_CTR,
    CASE WHEN c.ACTUAL_CLICKS > 0 THEN c.ACTUAL_CONVERSIONS / c.ACTUAL_CLICKS ELSE NULL END AS ACTUAL_CONVERSION_RATE,
    CASE WHEN c.MEDIA_BUDGET > 0 THEN c.ACTUAL_IMPRESSIONS / (c.MEDIA_BUDGET / 1000) ELSE NULL END AS EFFICIENCY_CPM,
    CASE WHEN c.ACTUAL_CLICKS > 0 THEN c.MEDIA_BUDGET / c.ACTUAL_CLICKS ELSE NULL END AS ACTUAL_CPC,
    CASE WHEN c.ACTUAL_CONVERSIONS > 0 THEN c.MEDIA_BUDGET / c.ACTUAL_CONVERSIONS ELSE NULL END AS ACTUAL_CPA,
    CASE WHEN c.TARGET_ROAS > 0 THEN c.ACTUAL_ROAS / c.TARGET_ROAS ELSE NULL END AS ROAS_PERFORMANCE_INDEX,
    YEAR(c.START_DATE) AS CAMPAIGN_YEAR,
    QUARTER(c.START_DATE) AS CAMPAIGN_QUARTER,
    MONTH(c.START_DATE) AS CAMPAIGN_MONTH,
    c.CREATED_DATE,
    c.UPDATED_DATE
FROM INNOCEAN_INTELLIGENCE.RAW.CAMPAIGNS c
LEFT JOIN INNOCEAN_INTELLIGENCE.RAW.CLIENTS cl ON c.CLIENT_ID = cl.CLIENT_ID;

-- ============================================================================
-- VIEW 2: CLIENT HEALTH ANALYTICS - Client relationship and financial health
-- ============================================================================

CREATE OR REPLACE VIEW V_CLIENT_HEALTH AS
SELECT
    cl.CLIENT_ID,
    cl.CLIENT_NAME,
    cl.PARENT_COMPANY,
    cl.INDUSTRY,
    cl.CLIENT_SEGMENT,
    cl.RELATIONSHIP_TYPE,
    cl.CONTRACT_START_DATE,
    cl.CONTRACT_END_DATE,
    cl.ANNUAL_BUDGET,
    cl.SATISFACTION_SCORE,
    cl.NPS_SCORE,
    cl.STATUS AS CLIENT_STATUS,
    COUNT(DISTINCT c.CAMPAIGN_ID) AS TOTAL_CAMPAIGNS,
    COUNT(DISTINCT CASE WHEN c.STATUS = 'COMPLETED' THEN c.CAMPAIGN_ID END) AS COMPLETED_CAMPAIGNS,
    COUNT(DISTINCT CASE WHEN c.STATUS = 'IN_FLIGHT' THEN c.CAMPAIGN_ID END) AS ACTIVE_CAMPAIGNS,
    SUM(c.TOTAL_BUDGET) AS TOTAL_CAMPAIGN_BUDGET,
    SUM(c.MEDIA_BUDGET) AS TOTAL_MEDIA_SPEND,
    AVG(c.ACTUAL_ROAS) AS AVG_CAMPAIGN_ROAS,
    COUNT(DISTINCT p.PROJECT_ID) AS TOTAL_PROJECTS,
    SUM(p.ESTIMATED_BUDGET) AS TOTAL_PROJECT_BUDGET,
    SUM(p.ACTUAL_COST) AS TOTAL_PROJECT_COST,
    AVG(p.PROFIT_MARGIN) AS AVG_PROJECT_MARGIN,
    COUNT(DISTINCT i.INVOICE_ID) AS TOTAL_INVOICES,
    SUM(i.TOTAL_AMOUNT) AS TOTAL_BILLED,
    SUM(i.AMOUNT_PAID) AS TOTAL_COLLECTED,
    SUM(i.TOTAL_AMOUNT) - SUM(i.AMOUNT_PAID) AS OUTSTANDING_BALANCE,
    COUNT(DISTINCT CASE WHEN i.STATUS = 'OVERDUE' THEN i.INVOICE_ID END) AS OVERDUE_INVOICES,
    DATEDIFF(DAY, cl.CONTRACT_START_DATE, CURRENT_DATE()) AS RELATIONSHIP_TENURE_DAYS,
    DATEDIFF(DAY, CURRENT_DATE(), cl.CONTRACT_END_DATE) AS DAYS_UNTIL_CONTRACT_END,
    CASE 
        WHEN cl.NPS_SCORE >= 50 AND cl.SATISFACTION_SCORE >= 8 THEN 'EXCELLENT'
        WHEN cl.NPS_SCORE >= 20 AND cl.SATISFACTION_SCORE >= 6 THEN 'GOOD'
        WHEN cl.NPS_SCORE >= 0 AND cl.SATISFACTION_SCORE >= 5 THEN 'FAIR'
        ELSE 'AT_RISK'
    END AS CLIENT_HEALTH_STATUS
FROM INNOCEAN_INTELLIGENCE.RAW.CLIENTS cl
LEFT JOIN INNOCEAN_INTELLIGENCE.RAW.CAMPAIGNS c ON cl.CLIENT_ID = c.CLIENT_ID
LEFT JOIN INNOCEAN_INTELLIGENCE.RAW.PROJECTS p ON cl.CLIENT_ID = p.CLIENT_ID
LEFT JOIN INNOCEAN_INTELLIGENCE.RAW.INVOICES i ON cl.CLIENT_ID = i.CLIENT_ID
GROUP BY
    cl.CLIENT_ID, cl.CLIENT_NAME, cl.PARENT_COMPANY, cl.INDUSTRY, cl.CLIENT_SEGMENT,
    cl.RELATIONSHIP_TYPE, cl.CONTRACT_START_DATE, cl.CONTRACT_END_DATE, cl.ANNUAL_BUDGET,
    cl.SATISFACTION_SCORE, cl.NPS_SCORE, cl.STATUS;

-- ============================================================================
-- VIEW 3: MEDIA PERFORMANCE ANALYTICS - Channel and placement performance
-- ============================================================================

CREATE OR REPLACE VIEW V_MEDIA_PERFORMANCE_ANALYTICS AS
SELECT
    mp.PLACEMENT_ID,
    mp.CAMPAIGN_ID,
    c.CAMPAIGN_NAME,
    c.CAMPAIGN_TYPE,
    cl.CLIENT_ID,
    cl.CLIENT_NAME,
    mp.CHANNEL,
    mp.PLATFORM,
    mp.PLACEMENT_TYPE,
    mp.TARGETING_TYPE,
    mp.BUYING_METHOD,
    mp.START_DATE AS PLACEMENT_START_DATE,
    mp.END_DATE AS PLACEMENT_END_DATE,
    mp.STATUS AS PLACEMENT_STATUS,
    mp.PLANNED_SPEND,
    mp.ACTUAL_SPEND,
    mp.PLANNED_IMPRESSIONS,
    mp.CPM_RATE,
    mp.CPC_RATE,
    mp.CPV_RATE,
    SUM(perf.IMPRESSIONS) AS DELIVERED_IMPRESSIONS,
    SUM(perf.REACH) AS TOTAL_REACH,
    AVG(perf.FREQUENCY) AS AVG_FREQUENCY,
    SUM(perf.CLICKS) AS TOTAL_CLICKS,
    SUM(perf.VIDEO_VIEWS) AS TOTAL_VIDEO_VIEWS,
    SUM(perf.VIDEO_COMPLETIONS) AS TOTAL_VIDEO_COMPLETIONS,
    SUM(perf.ENGAGEMENTS) AS TOTAL_ENGAGEMENTS,
    SUM(perf.CONVERSIONS) AS TOTAL_CONVERSIONS,
    SUM(perf.CONVERSION_VALUE) AS TOTAL_CONVERSION_VALUE,
    SUM(perf.SPEND) AS TOTAL_SPEND,
    CASE WHEN SUM(perf.IMPRESSIONS) > 0 THEN SUM(perf.CLICKS) / SUM(perf.IMPRESSIONS) ELSE NULL END AS CTR,
    CASE WHEN SUM(perf.VIDEO_VIEWS) > 0 THEN SUM(perf.VIDEO_COMPLETIONS) / SUM(perf.VIDEO_VIEWS) ELSE NULL END AS VIDEO_COMPLETION_RATE,
    CASE WHEN SUM(perf.IMPRESSIONS) > 0 THEN SUM(perf.ENGAGEMENTS) / SUM(perf.IMPRESSIONS) ELSE NULL END AS ENGAGEMENT_RATE,
    CASE WHEN SUM(perf.CLICKS) > 0 THEN SUM(perf.CONVERSIONS) / SUM(perf.CLICKS) ELSE NULL END AS CONVERSION_RATE,
    CASE WHEN SUM(perf.SPEND) > 0 THEN SUM(perf.IMPRESSIONS) / (SUM(perf.SPEND) / 1000) ELSE NULL END AS EFFICIENCY_CPM,
    CASE WHEN SUM(perf.CLICKS) > 0 THEN SUM(perf.SPEND) / SUM(perf.CLICKS) ELSE NULL END AS ACTUAL_CPC,
    CASE WHEN SUM(perf.CONVERSIONS) > 0 THEN SUM(perf.SPEND) / SUM(perf.CONVERSIONS) ELSE NULL END AS ACTUAL_CPA,
    CASE WHEN SUM(perf.SPEND) > 0 THEN SUM(perf.CONVERSION_VALUE) / SUM(perf.SPEND) ELSE NULL END AS ROAS,
    AVG(perf.VIEWABILITY_RATE) AS AVG_VIEWABILITY,
    AVG(perf.BRAND_SAFETY_SCORE) AS AVG_BRAND_SAFETY
FROM INNOCEAN_INTELLIGENCE.RAW.MEDIA_PLACEMENTS mp
LEFT JOIN INNOCEAN_INTELLIGENCE.RAW.CAMPAIGNS c ON mp.CAMPAIGN_ID = c.CAMPAIGN_ID
LEFT JOIN INNOCEAN_INTELLIGENCE.RAW.CLIENTS cl ON c.CLIENT_ID = cl.CLIENT_ID
LEFT JOIN INNOCEAN_INTELLIGENCE.RAW.MEDIA_PERFORMANCE perf ON mp.PLACEMENT_ID = perf.PLACEMENT_ID
GROUP BY
    mp.PLACEMENT_ID, mp.CAMPAIGN_ID, c.CAMPAIGN_NAME, c.CAMPAIGN_TYPE, cl.CLIENT_ID, cl.CLIENT_NAME,
    mp.CHANNEL, mp.PLATFORM, mp.PLACEMENT_TYPE, mp.TARGETING_TYPE, mp.BUYING_METHOD,
    mp.START_DATE, mp.END_DATE, mp.STATUS, mp.PLANNED_SPEND, mp.ACTUAL_SPEND,
    mp.PLANNED_IMPRESSIONS, mp.CPM_RATE, mp.CPC_RATE, mp.CPV_RATE;

-- ============================================================================
-- VIEW 4: CREATIVE PERFORMANCE - Asset performance and analysis
-- ============================================================================

CREATE OR REPLACE VIEW V_CREATIVE_PERFORMANCE AS
SELECT
    ca.ASSET_ID,
    ca.ASSET_NAME,
    ca.ASSET_TYPE,
    ca.FORMAT,
    ca.DURATION_SECONDS,
    ca.CONCEPT_NAME,
    ca.HEADLINE,
    ca.CTA_TEXT,
    ca.LANGUAGE,
    ca.VERSION_NUMBER,
    ca.APPROVAL_STATUS,
    ca.PERFORMANCE_RATING,
    ca.PRODUCTION_COST,
    ca.TALENT_COST,
    ca.PRODUCTION_COST + ca.TALENT_COST AS TOTAL_CREATIVE_COST,
    c.CAMPAIGN_ID,
    c.CAMPAIGN_NAME,
    c.CAMPAIGN_TYPE,
    cl.CLIENT_ID,
    cl.CLIENT_NAME,
    COUNT(DISTINCT mp.PLACEMENT_ID) AS PLACEMENT_COUNT,
    SUM(perf.IMPRESSIONS) AS TOTAL_IMPRESSIONS,
    SUM(perf.CLICKS) AS TOTAL_CLICKS,
    SUM(perf.VIDEO_VIEWS) AS TOTAL_VIDEO_VIEWS,
    SUM(perf.VIDEO_COMPLETIONS) AS TOTAL_VIDEO_COMPLETIONS,
    SUM(perf.ENGAGEMENTS) AS TOTAL_ENGAGEMENTS,
    SUM(perf.CONVERSIONS) AS TOTAL_CONVERSIONS,
    CASE WHEN SUM(perf.IMPRESSIONS) > 0 THEN SUM(perf.CLICKS) / SUM(perf.IMPRESSIONS) ELSE NULL END AS CTR,
    CASE WHEN SUM(perf.VIDEO_VIEWS) > 0 THEN SUM(perf.VIDEO_COMPLETIONS) / SUM(perf.VIDEO_VIEWS) ELSE NULL END AS VIDEO_COMPLETION_RATE,
    CASE WHEN SUM(perf.IMPRESSIONS) > 0 THEN SUM(perf.ENGAGEMENTS) / SUM(perf.IMPRESSIONS) ELSE NULL END AS ENGAGEMENT_RATE,
    CASE WHEN (ca.PRODUCTION_COST + ca.TALENT_COST) > 0 AND SUM(perf.IMPRESSIONS) > 0 
        THEN (ca.PRODUCTION_COST + ca.TALENT_COST) / (SUM(perf.IMPRESSIONS) / 1000000) 
        ELSE NULL END AS COST_PER_MILLION_IMPRESSIONS
FROM INNOCEAN_INTELLIGENCE.RAW.CREATIVE_ASSETS ca
LEFT JOIN INNOCEAN_INTELLIGENCE.RAW.CAMPAIGNS c ON ca.CAMPAIGN_ID = c.CAMPAIGN_ID
LEFT JOIN INNOCEAN_INTELLIGENCE.RAW.CLIENTS cl ON c.CLIENT_ID = cl.CLIENT_ID
LEFT JOIN INNOCEAN_INTELLIGENCE.RAW.MEDIA_PLACEMENTS mp ON ca.ASSET_ID = mp.ASSET_ID
LEFT JOIN INNOCEAN_INTELLIGENCE.RAW.MEDIA_PERFORMANCE perf ON mp.PLACEMENT_ID = perf.PLACEMENT_ID
GROUP BY
    ca.ASSET_ID, ca.ASSET_NAME, ca.ASSET_TYPE, ca.FORMAT, ca.DURATION_SECONDS, ca.CONCEPT_NAME,
    ca.HEADLINE, ca.CTA_TEXT, ca.LANGUAGE, ca.VERSION_NUMBER, ca.APPROVAL_STATUS, ca.PERFORMANCE_RATING,
    ca.PRODUCTION_COST, ca.TALENT_COST, c.CAMPAIGN_ID, c.CAMPAIGN_NAME, c.CAMPAIGN_TYPE,
    cl.CLIENT_ID, cl.CLIENT_NAME;

-- ============================================================================
-- VIEW 5: EMPLOYEE UTILIZATION - Resource allocation and capacity
-- ============================================================================

CREATE OR REPLACE VIEW V_EMPLOYEE_UTILIZATION AS
SELECT
    e.EMPLOYEE_ID,
    e.FIRST_NAME,
    e.LAST_NAME,
    e.FIRST_NAME || ' ' || e.LAST_NAME AS FULL_NAME,
    e.EMAIL,
    e.DEPARTMENT,
    e.TITLE,
    e.EMPLOYMENT_TYPE,
    e.HIRE_DATE,
    e.STATUS AS EMPLOYEE_STATUS,
    e.HOURLY_RATE,
    e.BILLABLE_RATE,
    e.UTILIZATION_TARGET,
    e.SKILLS,
    COUNT(DISTINCT t.PROJECT_ID) AS PROJECTS_WORKED,
    SUM(t.HOURS_WORKED) AS TOTAL_HOURS_WORKED,
    SUM(t.BILLABLE_HOURS) AS TOTAL_BILLABLE_HOURS,
    SUM(t.BILLABLE_HOURS) * e.BILLABLE_RATE AS TOTAL_BILLABLE_VALUE,
    CASE WHEN SUM(t.HOURS_WORKED) > 0 THEN SUM(t.BILLABLE_HOURS) / SUM(t.HOURS_WORKED) ELSE NULL END AS BILLABILITY_RATE,
    COUNT(DISTINCT CASE WHEN t.TASK_TYPE = 'CREATIVE' THEN t.TIMESHEET_ID END) AS CREATIVE_TASKS,
    COUNT(DISTINCT CASE WHEN t.TASK_TYPE = 'MEETINGS' THEN t.TIMESHEET_ID END) AS MEETING_TASKS,
    COUNT(DISTINCT CASE WHEN t.TASK_TYPE = 'ADMIN' THEN t.TIMESHEET_ID END) AS ADMIN_TASKS
FROM INNOCEAN_INTELLIGENCE.RAW.EMPLOYEES e
LEFT JOIN INNOCEAN_INTELLIGENCE.RAW.TIMESHEETS t ON e.EMPLOYEE_ID = t.EMPLOYEE_ID
GROUP BY
    e.EMPLOYEE_ID, e.FIRST_NAME, e.LAST_NAME, e.EMAIL, e.DEPARTMENT, e.TITLE,
    e.EMPLOYMENT_TYPE, e.HIRE_DATE, e.STATUS, e.HOURLY_RATE, e.BILLABLE_RATE,
    e.UTILIZATION_TARGET, e.SKILLS;

-- ============================================================================
-- VIEW 6: PROJECT PROFITABILITY - Project financial performance
-- ============================================================================

CREATE OR REPLACE VIEW V_PROJECT_PROFITABILITY AS
SELECT
    p.PROJECT_ID,
    p.PROJECT_NAME,
    p.PROJECT_TYPE,
    p.BILLING_TYPE,
    p.STATUS AS PROJECT_STATUS,
    p.START_DATE AS PROJECT_START_DATE,
    p.END_DATE AS PROJECT_END_DATE,
    DATEDIFF(DAY, p.START_DATE, COALESCE(p.END_DATE, CURRENT_DATE())) AS PROJECT_DURATION_DAYS,
    cl.CLIENT_ID,
    cl.CLIENT_NAME,
    c.CAMPAIGN_ID,
    c.CAMPAIGN_NAME,
    p.ESTIMATED_HOURS,
    p.ACTUAL_HOURS,
    CASE WHEN p.ESTIMATED_HOURS > 0 THEN p.ACTUAL_HOURS / p.ESTIMATED_HOURS ELSE NULL END AS HOURS_VARIANCE_PCT,
    p.ESTIMATED_BUDGET,
    p.ACTUAL_COST,
    p.ESTIMATED_BUDGET - p.ACTUAL_COST AS BUDGET_VARIANCE,
    CASE WHEN p.ESTIMATED_BUDGET > 0 THEN (p.ESTIMATED_BUDGET - p.ACTUAL_COST) / p.ESTIMATED_BUDGET ELSE NULL END AS BUDGET_VARIANCE_PCT,
    p.PROFIT_MARGIN,
    e.FIRST_NAME || ' ' || e.LAST_NAME AS PROJECT_LEAD,
    COUNT(DISTINCT t.EMPLOYEE_ID) AS TEAM_SIZE,
    SUM(t.HOURS_WORKED) AS TOTAL_HOURS_LOGGED,
    SUM(t.BILLABLE_HOURS) AS TOTAL_BILLABLE_HOURS,
    CASE WHEN SUM(t.HOURS_WORKED) > 0 THEN SUM(t.BILLABLE_HOURS) / SUM(t.HOURS_WORKED) ELSE NULL END AS PROJECT_BILLABILITY
FROM INNOCEAN_INTELLIGENCE.RAW.PROJECTS p
LEFT JOIN INNOCEAN_INTELLIGENCE.RAW.CLIENTS cl ON p.CLIENT_ID = cl.CLIENT_ID
LEFT JOIN INNOCEAN_INTELLIGENCE.RAW.CAMPAIGNS c ON p.CAMPAIGN_ID = c.CAMPAIGN_ID
LEFT JOIN INNOCEAN_INTELLIGENCE.RAW.EMPLOYEES e ON p.PROJECT_LEAD_ID = e.EMPLOYEE_ID
LEFT JOIN INNOCEAN_INTELLIGENCE.RAW.TIMESHEETS t ON p.PROJECT_ID = t.PROJECT_ID
GROUP BY
    p.PROJECT_ID, p.PROJECT_NAME, p.PROJECT_TYPE, p.BILLING_TYPE, p.STATUS,
    p.START_DATE, p.END_DATE, cl.CLIENT_ID, cl.CLIENT_NAME, c.CAMPAIGN_ID, c.CAMPAIGN_NAME,
    p.ESTIMATED_HOURS, p.ACTUAL_HOURS, p.ESTIMATED_BUDGET, p.ACTUAL_COST, p.PROFIT_MARGIN,
    e.FIRST_NAME, e.LAST_NAME;

-- ============================================================================
-- VIEW 7: REVENUE ANALYTICS - Financial performance and billing
-- ============================================================================

CREATE OR REPLACE VIEW V_REVENUE_ANALYTICS AS
SELECT
    i.INVOICE_ID,
    i.INVOICE_NUMBER,
    i.INVOICE_DATE,
    i.DUE_DATE,
    i.STATUS AS INVOICE_STATUS,
    i.PAYMENT_TERMS,
    cl.CLIENT_ID,
    cl.CLIENT_NAME,
    cl.CLIENT_SEGMENT,
    cl.RELATIONSHIP_TYPE,
    p.PROJECT_ID,
    p.PROJECT_NAME,
    p.PROJECT_TYPE,
    i.SUBTOTAL,
    i.TAX_AMOUNT,
    i.TOTAL_AMOUNT,
    i.AMOUNT_PAID,
    i.TOTAL_AMOUNT - i.AMOUNT_PAID AS OUTSTANDING_AMOUNT,
    i.PAYMENT_DATE,
    CASE WHEN i.PAYMENT_DATE IS NOT NULL THEN DATEDIFF(DAY, i.INVOICE_DATE, i.PAYMENT_DATE) ELSE NULL END AS DAYS_TO_PAYMENT,
    CASE WHEN i.STATUS = 'OVERDUE' THEN DATEDIFF(DAY, i.DUE_DATE, CURRENT_DATE()) ELSE 0 END AS DAYS_OVERDUE,
    YEAR(i.INVOICE_DATE) AS INVOICE_YEAR,
    QUARTER(i.INVOICE_DATE) AS INVOICE_QUARTER,
    MONTH(i.INVOICE_DATE) AS INVOICE_MONTH,
    COUNT(li.LINE_ITEM_ID) AS LINE_ITEM_COUNT,
    SUM(CASE WHEN li.CATEGORY = 'MEDIA' THEN li.LINE_TOTAL ELSE 0 END) AS MEDIA_REVENUE,
    SUM(CASE WHEN li.CATEGORY = 'PRODUCTION' THEN li.LINE_TOTAL ELSE 0 END) AS PRODUCTION_REVENUE,
    SUM(CASE WHEN li.CATEGORY = 'FEES' THEN li.LINE_TOTAL ELSE 0 END) AS FEE_REVENUE,
    SUM(CASE WHEN li.CATEGORY = 'TALENT' THEN li.LINE_TOTAL ELSE 0 END) AS TALENT_REVENUE
FROM INNOCEAN_INTELLIGENCE.RAW.INVOICES i
LEFT JOIN INNOCEAN_INTELLIGENCE.RAW.CLIENTS cl ON i.CLIENT_ID = cl.CLIENT_ID
LEFT JOIN INNOCEAN_INTELLIGENCE.RAW.PROJECTS p ON i.PROJECT_ID = p.PROJECT_ID
LEFT JOIN INNOCEAN_INTELLIGENCE.RAW.INVOICE_LINE_ITEMS li ON i.INVOICE_ID = li.INVOICE_ID
GROUP BY
    i.INVOICE_ID, i.INVOICE_NUMBER, i.INVOICE_DATE, i.DUE_DATE, i.STATUS, i.PAYMENT_TERMS,
    cl.CLIENT_ID, cl.CLIENT_NAME, cl.CLIENT_SEGMENT, cl.RELATIONSHIP_TYPE,
    p.PROJECT_ID, p.PROJECT_NAME, p.PROJECT_TYPE, i.SUBTOTAL, i.TAX_AMOUNT, i.TOTAL_AMOUNT,
    i.AMOUNT_PAID, i.PAYMENT_DATE;

-- ============================================================================
-- VIEW 8: CHANNEL PERFORMANCE SUMMARY - Aggregated channel metrics
-- ============================================================================

CREATE OR REPLACE VIEW V_CHANNEL_PERFORMANCE_SUMMARY AS
SELECT
    mp.CHANNEL,
    mp.PLATFORM,
    COUNT(DISTINCT mp.PLACEMENT_ID) AS PLACEMENT_COUNT,
    COUNT(DISTINCT mp.CAMPAIGN_ID) AS CAMPAIGN_COUNT,
    COUNT(DISTINCT c.CLIENT_ID) AS CLIENT_COUNT,
    SUM(mp.PLANNED_SPEND) AS TOTAL_PLANNED_SPEND,
    SUM(mp.ACTUAL_SPEND) AS TOTAL_ACTUAL_SPEND,
    SUM(perf.IMPRESSIONS) AS TOTAL_IMPRESSIONS,
    SUM(perf.REACH) AS TOTAL_REACH,
    SUM(perf.CLICKS) AS TOTAL_CLICKS,
    SUM(perf.VIDEO_VIEWS) AS TOTAL_VIDEO_VIEWS,
    SUM(perf.VIDEO_COMPLETIONS) AS TOTAL_VIDEO_COMPLETIONS,
    SUM(perf.ENGAGEMENTS) AS TOTAL_ENGAGEMENTS,
    SUM(perf.CONVERSIONS) AS TOTAL_CONVERSIONS,
    SUM(perf.CONVERSION_VALUE) AS TOTAL_CONVERSION_VALUE,
    CASE WHEN SUM(perf.IMPRESSIONS) > 0 THEN SUM(perf.CLICKS) / SUM(perf.IMPRESSIONS) ELSE NULL END AS AVG_CTR,
    CASE WHEN SUM(perf.VIDEO_VIEWS) > 0 THEN SUM(perf.VIDEO_COMPLETIONS) / SUM(perf.VIDEO_VIEWS) ELSE NULL END AS AVG_VIDEO_COMPLETION_RATE,
    CASE WHEN SUM(perf.IMPRESSIONS) > 0 THEN SUM(perf.ENGAGEMENTS) / SUM(perf.IMPRESSIONS) ELSE NULL END AS AVG_ENGAGEMENT_RATE,
    CASE WHEN SUM(perf.SPEND) > 0 THEN SUM(perf.IMPRESSIONS) / (SUM(perf.SPEND) / 1000) ELSE NULL END AS AVG_CPM,
    CASE WHEN SUM(perf.CLICKS) > 0 THEN SUM(perf.SPEND) / SUM(perf.CLICKS) ELSE NULL END AS AVG_CPC,
    CASE WHEN SUM(perf.CONVERSIONS) > 0 THEN SUM(perf.SPEND) / SUM(perf.CONVERSIONS) ELSE NULL END AS AVG_CPA,
    CASE WHEN SUM(perf.SPEND) > 0 THEN SUM(perf.CONVERSION_VALUE) / SUM(perf.SPEND) ELSE NULL END AS AVG_ROAS,
    AVG(perf.VIEWABILITY_RATE) AS AVG_VIEWABILITY,
    AVG(perf.BRAND_SAFETY_SCORE) AS AVG_BRAND_SAFETY
FROM INNOCEAN_INTELLIGENCE.RAW.MEDIA_PLACEMENTS mp
LEFT JOIN INNOCEAN_INTELLIGENCE.RAW.CAMPAIGNS c ON mp.CAMPAIGN_ID = c.CAMPAIGN_ID
LEFT JOIN INNOCEAN_INTELLIGENCE.RAW.MEDIA_PERFORMANCE perf ON mp.PLACEMENT_ID = perf.PLACEMENT_ID
GROUP BY mp.CHANNEL, mp.PLATFORM;

-- ============================================================================
-- VIEW 9: TALENT USAGE ANALYTICS - Talent contracts and usage tracking
-- ============================================================================

CREATE OR REPLACE VIEW V_TALENT_ANALYTICS AS
SELECT
    t.TALENT_ID,
    t.TALENT_NAME,
    t.TALENT_TYPE,
    t.AGENCY_NAME,
    t.DAY_RATE,
    t.USAGE_RATE,
    t.EXCLUSIVITY_CATEGORY,
    t.STATUS AS TALENT_STATUS,
    COUNT(DISTINCT tu.USAGE_ID) AS TOTAL_USAGES,
    COUNT(DISTINCT tu.ASSET_ID) AS ASSETS_APPEARED_IN,
    COUNT(DISTINCT ca.CAMPAIGN_ID) AS CAMPAIGNS_APPEARED_IN,
    SUM(tu.USAGE_FEE) AS TOTAL_USAGE_FEES,
    COUNT(DISTINCT CASE WHEN tu.STATUS = 'ACTIVE' THEN tu.USAGE_ID END) AS ACTIVE_USAGES,
    COUNT(DISTINCT CASE WHEN tu.STATUS = 'PENDING_RENEWAL' THEN tu.USAGE_ID END) AS PENDING_RENEWALS,
    COUNT(DISTINCT CASE WHEN tu.STATUS = 'EXPIRED' THEN tu.USAGE_ID END) AS EXPIRED_USAGES,
    MIN(tu.START_DATE) AS FIRST_USAGE_DATE,
    MAX(tu.END_DATE) AS LAST_USAGE_END_DATE,
    MIN(CASE WHEN tu.STATUS = 'PENDING_RENEWAL' THEN tu.RENEWAL_DATE END) AS NEAREST_RENEWAL_DATE
FROM INNOCEAN_INTELLIGENCE.RAW.TALENT t
LEFT JOIN INNOCEAN_INTELLIGENCE.RAW.TALENT_USAGE tu ON t.TALENT_ID = tu.TALENT_ID
LEFT JOIN INNOCEAN_INTELLIGENCE.RAW.CREATIVE_ASSETS ca ON tu.ASSET_ID = ca.ASSET_ID
GROUP BY
    t.TALENT_ID, t.TALENT_NAME, t.TALENT_TYPE, t.AGENCY_NAME,
    t.DAY_RATE, t.USAGE_RATE, t.EXCLUSIVITY_CATEGORY, t.STATUS;

-- ============================================================================
-- VIEW 10: AUDIENCE SEGMENT PERFORMANCE - Targeting effectiveness
-- ============================================================================

CREATE OR REPLACE VIEW V_AUDIENCE_SEGMENT_PERFORMANCE AS
SELECT
    seg.SEGMENT_ID,
    seg.SEGMENT_NAME,
    seg.SEGMENT_TYPE,
    seg.DESCRIPTION AS SEGMENT_DESCRIPTION,
    seg.AGE_MIN,
    seg.AGE_MAX,
    seg.GENDER,
    seg.INCOME_MIN,
    seg.INCOME_MAX,
    seg.INTERESTS,
    seg.BEHAVIORS,
    seg.GEO_TARGETING,
    seg.ESTIMATED_SIZE,
    seg.DATA_SOURCE,
    COUNT(DISTINCT ca.CAMPAIGN_ID) AS CAMPAIGNS_TARGETED,
    SUM(ca.BUDGET_ALLOCATION) AS TOTAL_BUDGET_ALLOCATION,
    AVG(c.ACTUAL_ROAS) AS AVG_CAMPAIGN_ROAS,
    AVG(CASE WHEN c.ACTUAL_IMPRESSIONS > 0 THEN c.ACTUAL_CLICKS / c.ACTUAL_IMPRESSIONS ELSE NULL END) AS AVG_CTR,
    AVG(CASE WHEN c.ACTUAL_CLICKS > 0 THEN c.ACTUAL_CONVERSIONS / c.ACTUAL_CLICKS ELSE NULL END) AS AVG_CONVERSION_RATE
FROM INNOCEAN_INTELLIGENCE.RAW.AUDIENCE_SEGMENTS seg
LEFT JOIN INNOCEAN_INTELLIGENCE.RAW.CAMPAIGN_AUDIENCES ca ON seg.SEGMENT_ID = ca.SEGMENT_ID
LEFT JOIN INNOCEAN_INTELLIGENCE.RAW.CAMPAIGNS c ON ca.CAMPAIGN_ID = c.CAMPAIGN_ID
GROUP BY
    seg.SEGMENT_ID, seg.SEGMENT_NAME, seg.SEGMENT_TYPE, seg.DESCRIPTION,
    seg.AGE_MIN, seg.AGE_MAX, seg.GENDER, seg.INCOME_MIN, seg.INCOME_MAX,
    seg.INTERESTS, seg.BEHAVIORS, seg.GEO_TARGETING, seg.ESTIMATED_SIZE, seg.DATA_SOURCE;

-- ============================================================================
-- VERIFICATION
-- ============================================================================

SHOW VIEWS IN SCHEMA INNOCEAN_INTELLIGENCE.ANALYTICS;

/*
=============================================================================
VIEW CREATION COMPLETE

Views Created:
1. V_CAMPAIGN_360 - Comprehensive campaign performance
2. V_CLIENT_HEALTH - Client relationship health metrics
3. V_MEDIA_PERFORMANCE_ANALYTICS - Placement-level media metrics
4. V_CREATIVE_PERFORMANCE - Creative asset performance
5. V_EMPLOYEE_UTILIZATION - Resource allocation metrics
6. V_PROJECT_PROFITABILITY - Project financial performance
7. V_REVENUE_ANALYTICS - Billing and revenue metrics
8. V_CHANNEL_PERFORMANCE_SUMMARY - Aggregated channel performance
9. V_TALENT_ANALYTICS - Talent usage and contracts
10. V_AUDIENCE_SEGMENT_PERFORMANCE - Targeting effectiveness

Next Step: Run 05_create_semantic_views.sql
=============================================================================
*/
