/*
=============================================================================
INNOCEAN USA ADVERTISING INTELLIGENCE - TABLE DEFINITIONS
=============================================================================
Script: 02_create_tables.sql
Purpose: Create all tables for advertising agency data model
Created: January 2026
=============================================================================
*/

USE DATABASE INNOCEAN_INTELLIGENCE;
USE SCHEMA RAW;

-- ============================================================================
-- CORE ENTITY TABLES
-- ============================================================================

-- CLIENTS: Brand and account master data
CREATE OR REPLACE TABLE CLIENTS (
    CLIENT_ID VARCHAR(50) PRIMARY KEY,
    CLIENT_NAME VARCHAR(200) NOT NULL,
    PARENT_COMPANY VARCHAR(200),
    INDUSTRY VARCHAR(100),
    CLIENT_SEGMENT VARCHAR(50),  -- AUTOMOTIVE, RETAIL, CPG, TECHNOLOGY, FINANCIAL, ENTERTAINMENT
    RELATIONSHIP_TYPE VARCHAR(50),  -- AOR (Agency of Record), PROJECT, RETAINER
    CONTRACT_START_DATE DATE,
    CONTRACT_END_DATE DATE,
    ANNUAL_BUDGET NUMBER(15,2),
    PRIMARY_CONTACT_NAME VARCHAR(200),
    PRIMARY_CONTACT_EMAIL VARCHAR(200),
    BILLING_ADDRESS VARCHAR(500),
    SATISFACTION_SCORE NUMBER(3,1),  -- 1-10 scale
    NPS_SCORE NUMBER(3,0),  -- -100 to 100
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',  -- ACTIVE, INACTIVE, PROSPECT, CHURNED
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- CAMPAIGNS: Marketing campaign records
CREATE OR REPLACE TABLE CAMPAIGNS (
    CAMPAIGN_ID VARCHAR(50) PRIMARY KEY,
    CLIENT_ID VARCHAR(50) NOT NULL REFERENCES CLIENTS(CLIENT_ID),
    CAMPAIGN_NAME VARCHAR(300) NOT NULL,
    CAMPAIGN_TYPE VARCHAR(100),  -- BRAND_AWARENESS, PRODUCT_LAUNCH, SEASONAL, ALWAYS_ON, TACTICAL
    CAMPAIGN_OBJECTIVE VARCHAR(100),  -- AWARENESS, CONSIDERATION, CONVERSION, RETENTION, ADVOCACY
    START_DATE DATE,
    END_DATE DATE,
    TOTAL_BUDGET NUMBER(15,2),
    MEDIA_BUDGET NUMBER(15,2),
    PRODUCTION_BUDGET NUMBER(15,2),
    TARGET_AUDIENCE VARCHAR(500),
    TARGET_GEO VARCHAR(200),
    TARGET_IMPRESSIONS NUMBER(15,0),
    TARGET_REACH NUMBER(15,0),
    TARGET_FREQUENCY NUMBER(5,2),
    TARGET_CTR NUMBER(5,4),
    TARGET_CONVERSION_RATE NUMBER(5,4),
    TARGET_ROAS NUMBER(8,2),
    ACTUAL_IMPRESSIONS NUMBER(15,0),
    ACTUAL_REACH NUMBER(15,0),
    ACTUAL_CLICKS NUMBER(15,0),
    ACTUAL_CONVERSIONS NUMBER(15,0),
    ACTUAL_REVENUE NUMBER(15,2),
    ACTUAL_ROAS NUMBER(8,2),
    STATUS VARCHAR(20) DEFAULT 'PLANNED',  -- PLANNED, IN_FLIGHT, COMPLETED, PAUSED, CANCELLED
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- CREATIVE_ASSETS: Ads, videos, print materials, digital content
CREATE OR REPLACE TABLE CREATIVE_ASSETS (
    ASSET_ID VARCHAR(50) PRIMARY KEY,
    CAMPAIGN_ID VARCHAR(50) NOT NULL REFERENCES CAMPAIGNS(CAMPAIGN_ID),
    ASSET_NAME VARCHAR(300) NOT NULL,
    ASSET_TYPE VARCHAR(50),  -- VIDEO, DISPLAY, SOCIAL, PRINT, AUDIO, OOH
    FORMAT VARCHAR(50),  -- :30TV, :15TV, :06BUMPER, 300x250, 728x90, CAROUSEL, STORY, etc.
    DURATION_SECONDS NUMBER(10,0),
    DIMENSIONS VARCHAR(50),
    FILE_SIZE_MB NUMBER(10,2),
    LANGUAGE VARCHAR(20) DEFAULT 'EN',
    VERSION_NUMBER NUMBER(5,0) DEFAULT 1,
    CONCEPT_NAME VARCHAR(200),
    HEADLINE VARCHAR(500),
    BODY_COPY VARCHAR(2000),
    CTA_TEXT VARCHAR(100),
    PRODUCTION_COST NUMBER(12,2),
    TALENT_COST NUMBER(12,2),
    APPROVAL_STATUS VARCHAR(20) DEFAULT 'DRAFT',  -- DRAFT, IN_REVIEW, CLIENT_REVIEW, APPROVED, REJECTED
    APPROVED_DATE DATE,
    APPROVED_BY VARCHAR(200),
    PERFORMANCE_RATING NUMBER(3,1),  -- 1-10 based on engagement
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- MEDIA_PLACEMENTS: TV, digital, social, OOH media buys
CREATE OR REPLACE TABLE MEDIA_PLACEMENTS (
    PLACEMENT_ID VARCHAR(50) PRIMARY KEY,
    CAMPAIGN_ID VARCHAR(50) NOT NULL REFERENCES CAMPAIGNS(CAMPAIGN_ID),
    ASSET_ID VARCHAR(50) REFERENCES CREATIVE_ASSETS(ASSET_ID),
    CHANNEL VARCHAR(50),  -- TV, STREAMING, DIGITAL_DISPLAY, SOCIAL, SEARCH, OOH, RADIO, PRINT
    PLATFORM VARCHAR(100),  -- NBC, HULU, GOOGLE, META, TIKTOK, SPOTIFY, etc.
    PLACEMENT_TYPE VARCHAR(100),  -- PRIME_TIME, DAY_PART, PROGRAMMATIC, DIRECT, SPONSORSHIP
    TARGETING_TYPE VARCHAR(100),  -- DEMO, BEHAVIORAL, CONTEXTUAL, RETARGETING, LOOKALIKE
    START_DATE DATE,
    END_DATE DATE,
    PLANNED_SPEND NUMBER(12,2),
    ACTUAL_SPEND NUMBER(12,2),
    PLANNED_IMPRESSIONS NUMBER(15,0),
    CPM_RATE NUMBER(8,4),
    CPC_RATE NUMBER(8,4),
    CPV_RATE NUMBER(8,4),
    BUYING_METHOD VARCHAR(50),  -- UPFRONT, SCATTER, PROGRAMMATIC, DIRECT_IO
    STATUS VARCHAR(20) DEFAULT 'PLANNED',  -- PLANNED, BOOKED, LIVE, COMPLETED, CANCELLED
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- MEDIA_PERFORMANCE: Impressions, clicks, conversions, engagement
CREATE OR REPLACE TABLE MEDIA_PERFORMANCE (
    PERFORMANCE_ID VARCHAR(50) PRIMARY KEY,
    PLACEMENT_ID VARCHAR(50) NOT NULL REFERENCES MEDIA_PLACEMENTS(PLACEMENT_ID),
    PERFORMANCE_DATE DATE NOT NULL,
    IMPRESSIONS NUMBER(15,0) DEFAULT 0,
    REACH NUMBER(15,0) DEFAULT 0,
    FREQUENCY NUMBER(8,4) DEFAULT 0,
    CLICKS NUMBER(15,0) DEFAULT 0,
    VIDEO_VIEWS NUMBER(15,0) DEFAULT 0,
    VIDEO_COMPLETIONS NUMBER(15,0) DEFAULT 0,
    VIDEO_25_PCT NUMBER(15,0) DEFAULT 0,
    VIDEO_50_PCT NUMBER(15,0) DEFAULT 0,
    VIDEO_75_PCT NUMBER(15,0) DEFAULT 0,
    ENGAGEMENTS NUMBER(15,0) DEFAULT 0,
    LIKES NUMBER(15,0) DEFAULT 0,
    SHARES NUMBER(15,0) DEFAULT 0,
    COMMENTS NUMBER(15,0) DEFAULT 0,
    CONVERSIONS NUMBER(15,0) DEFAULT 0,
    CONVERSION_VALUE NUMBER(15,2) DEFAULT 0,
    SPEND NUMBER(12,2) DEFAULT 0,
    VIEWABILITY_RATE NUMBER(5,4),
    BRAND_SAFETY_SCORE NUMBER(5,2),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- EMPLOYEE AND RESOURCE TABLES
-- ============================================================================

-- EMPLOYEES: Staff and freelancer data
CREATE OR REPLACE TABLE EMPLOYEES (
    EMPLOYEE_ID VARCHAR(50) PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(200),
    DEPARTMENT VARCHAR(100),  -- CREATIVE, MEDIA, ACCOUNT, STRATEGY, PRODUCTION, FINANCE, HR
    TITLE VARCHAR(200),
    EMPLOYMENT_TYPE VARCHAR(20),  -- FTE, CONTRACTOR, FREELANCE
    HIRE_DATE DATE,
    TERMINATION_DATE DATE,
    HOURLY_RATE NUMBER(8,2),
    ANNUAL_SALARY NUMBER(12,2),
    BILLABLE_RATE NUMBER(8,2),
    MANAGER_ID VARCHAR(50),
    SKILLS VARCHAR(1000),  -- Comma-separated list
    CERTIFICATIONS VARCHAR(500),
    UTILIZATION_TARGET NUMBER(5,2) DEFAULT 0.80,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- PROJECTS: Client project records
CREATE OR REPLACE TABLE PROJECTS (
    PROJECT_ID VARCHAR(50) PRIMARY KEY,
    CLIENT_ID VARCHAR(50) NOT NULL REFERENCES CLIENTS(CLIENT_ID),
    CAMPAIGN_ID VARCHAR(50) REFERENCES CAMPAIGNS(CAMPAIGN_ID),
    PROJECT_NAME VARCHAR(300) NOT NULL,
    PROJECT_TYPE VARCHAR(100),  -- CAMPAIGN, PRODUCTION, STRATEGY, RESEARCH, RETAINER_WORK
    START_DATE DATE,
    END_DATE DATE,
    ESTIMATED_HOURS NUMBER(10,2),
    ACTUAL_HOURS NUMBER(10,2),
    ESTIMATED_BUDGET NUMBER(12,2),
    ACTUAL_COST NUMBER(12,2),
    BILLING_TYPE VARCHAR(50),  -- FIXED_FEE, HOURLY, RETAINER, COMMISSION
    PROJECT_LEAD_ID VARCHAR(50) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',  -- PLANNED, ACTIVE, ON_HOLD, COMPLETED, CANCELLED
    PROFIT_MARGIN NUMBER(5,4),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- TIMESHEETS: Hours and resource allocation
CREATE OR REPLACE TABLE TIMESHEETS (
    TIMESHEET_ID VARCHAR(50) PRIMARY KEY,
    EMPLOYEE_ID VARCHAR(50) NOT NULL REFERENCES EMPLOYEES(EMPLOYEE_ID),
    PROJECT_ID VARCHAR(50) NOT NULL REFERENCES PROJECTS(PROJECT_ID),
    WORK_DATE DATE NOT NULL,
    HOURS_WORKED NUMBER(5,2) NOT NULL,
    BILLABLE_HOURS NUMBER(5,2),
    TASK_TYPE VARCHAR(100),  -- CREATIVE, STRATEGY, MEETINGS, ADMIN, PRODUCTION, REVIEW
    TASK_DESCRIPTION VARCHAR(500),
    APPROVED BOOLEAN DEFAULT FALSE,
    APPROVED_BY VARCHAR(50),
    APPROVED_DATE DATE,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- FINANCIAL TABLES
-- ============================================================================

-- INVOICES: Client billing records
CREATE OR REPLACE TABLE INVOICES (
    INVOICE_ID VARCHAR(50) PRIMARY KEY,
    CLIENT_ID VARCHAR(50) NOT NULL REFERENCES CLIENTS(CLIENT_ID),
    PROJECT_ID VARCHAR(50) REFERENCES PROJECTS(PROJECT_ID),
    INVOICE_NUMBER VARCHAR(50) NOT NULL,
    INVOICE_DATE DATE NOT NULL,
    DUE_DATE DATE NOT NULL,
    SUBTOTAL NUMBER(15,2),
    TAX_AMOUNT NUMBER(15,2),
    TOTAL_AMOUNT NUMBER(15,2),
    AMOUNT_PAID NUMBER(15,2) DEFAULT 0,
    PAYMENT_DATE DATE,
    STATUS VARCHAR(20) DEFAULT 'DRAFT',  -- DRAFT, SENT, PAID, OVERDUE, CANCELLED, DISPUTED
    PAYMENT_TERMS VARCHAR(50),  -- NET30, NET45, NET60
    NOTES VARCHAR(1000),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- INVOICE_LINE_ITEMS: Detailed billing breakdown
CREATE OR REPLACE TABLE INVOICE_LINE_ITEMS (
    LINE_ITEM_ID VARCHAR(50) PRIMARY KEY,
    INVOICE_ID VARCHAR(50) NOT NULL REFERENCES INVOICES(INVOICE_ID),
    DESCRIPTION VARCHAR(500) NOT NULL,
    QUANTITY NUMBER(10,2),
    UNIT_PRICE NUMBER(12,2),
    LINE_TOTAL NUMBER(15,2),
    CATEGORY VARCHAR(100),  -- MEDIA, PRODUCTION, FEES, TALENT, TRAVEL, MISC
    BILLABLE_TYPE VARCHAR(50),  -- TIME, EXPENSE, COMMISSION, MARKUP
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- VENDOR AND TALENT TABLES
-- ============================================================================

-- VENDORS: Production partners and media vendors
CREATE OR REPLACE TABLE VENDORS (
    VENDOR_ID VARCHAR(50) PRIMARY KEY,
    VENDOR_NAME VARCHAR(200) NOT NULL,
    VENDOR_TYPE VARCHAR(100),  -- PRODUCTION, POST, MUSIC, PHOTOGRAPHY, MEDIA, RESEARCH, TECH
    CONTACT_NAME VARCHAR(200),
    CONTACT_EMAIL VARCHAR(200),
    CONTACT_PHONE VARCHAR(50),
    ADDRESS VARCHAR(500),
    PAYMENT_TERMS VARCHAR(50),
    PREFERRED_VENDOR BOOLEAN DEFAULT FALSE,
    QUALITY_RATING NUMBER(3,1),  -- 1-10
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- VENDOR_CONTRACTS: Partner agreements
CREATE OR REPLACE TABLE VENDOR_CONTRACTS (
    CONTRACT_ID VARCHAR(50) PRIMARY KEY,
    VENDOR_ID VARCHAR(50) NOT NULL REFERENCES VENDORS(VENDOR_ID),
    CONTRACT_NAME VARCHAR(200),
    START_DATE DATE,
    END_DATE DATE,
    CONTRACT_VALUE NUMBER(15,2),
    TERMS VARCHAR(2000),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',  -- DRAFT, ACTIVE, EXPIRED, TERMINATED
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- TALENT: Actors, voiceover artists, models
CREATE OR REPLACE TABLE TALENT (
    TALENT_ID VARCHAR(50) PRIMARY KEY,
    TALENT_NAME VARCHAR(200) NOT NULL,
    TALENT_TYPE VARCHAR(100),  -- ACTOR, MODEL, VOICEOVER, INFLUENCER, CELEBRITY
    AGENCY_NAME VARCHAR(200),
    AGENT_NAME VARCHAR(200),
    AGENT_EMAIL VARCHAR(200),
    DAY_RATE NUMBER(12,2),
    USAGE_RATE NUMBER(12,2),
    EXCLUSIVITY_CATEGORY VARCHAR(100),  -- AUTOMOTIVE, NONE, BRAND_SPECIFIC
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- TALENT_USAGE: Talent appearances in campaigns
CREATE OR REPLACE TABLE TALENT_USAGE (
    USAGE_ID VARCHAR(50) PRIMARY KEY,
    TALENT_ID VARCHAR(50) NOT NULL REFERENCES TALENT(TALENT_ID),
    ASSET_ID VARCHAR(50) NOT NULL REFERENCES CREATIVE_ASSETS(ASSET_ID),
    USAGE_TYPE VARCHAR(100),  -- BROADCAST, DIGITAL, SOCIAL, PRINT, OOH
    TERRITORY VARCHAR(100),  -- US, NORTH_AMERICA, GLOBAL, REGIONAL
    START_DATE DATE,
    END_DATE DATE,
    USAGE_FEE NUMBER(12,2),
    RENEWAL_DATE DATE,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',  -- ACTIVE, EXPIRED, PENDING_RENEWAL
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- AUDIENCE AND TARGETING TABLES
-- ============================================================================

-- AUDIENCE_SEGMENTS: Target demographic definitions
CREATE OR REPLACE TABLE AUDIENCE_SEGMENTS (
    SEGMENT_ID VARCHAR(50) PRIMARY KEY,
    SEGMENT_NAME VARCHAR(200) NOT NULL,
    SEGMENT_TYPE VARCHAR(100),  -- DEMOGRAPHIC, BEHAVIORAL, INTEREST, CUSTOM, LOOKALIKE
    DESCRIPTION VARCHAR(1000),
    AGE_MIN NUMBER(3,0),
    AGE_MAX NUMBER(3,0),
    GENDER VARCHAR(20),
    INCOME_MIN NUMBER(12,0),
    INCOME_MAX NUMBER(12,0),
    INTERESTS VARCHAR(1000),
    BEHAVIORS VARCHAR(1000),
    GEO_TARGETING VARCHAR(500),
    ESTIMATED_SIZE NUMBER(15,0),
    DATA_SOURCE VARCHAR(100),  -- FIRST_PARTY, THIRD_PARTY, PLATFORM, RESEARCH
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- CAMPAIGN_AUDIENCES: Campaign targeting assignments
CREATE OR REPLACE TABLE CAMPAIGN_AUDIENCES (
    ASSIGNMENT_ID VARCHAR(50) PRIMARY KEY,
    CAMPAIGN_ID VARCHAR(50) NOT NULL REFERENCES CAMPAIGNS(CAMPAIGN_ID),
    SEGMENT_ID VARCHAR(50) NOT NULL REFERENCES AUDIENCE_SEGMENTS(SEGMENT_ID),
    PRIORITY NUMBER(3,0) DEFAULT 1,  -- 1 = Primary, 2 = Secondary, etc.
    BUDGET_ALLOCATION NUMBER(5,4),  -- Percentage of campaign budget
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- UNSTRUCTURED DATA TABLES (FOR CORTEX SEARCH)
-- ============================================================================

-- CREATIVE_BRIEFS: Unstructured creative brief documents
CREATE OR REPLACE TABLE CREATIVE_BRIEFS (
    BRIEF_ID VARCHAR(50) PRIMARY KEY,
    CLIENT_ID VARCHAR(50) NOT NULL REFERENCES CLIENTS(CLIENT_ID),
    CAMPAIGN_ID VARCHAR(50) REFERENCES CAMPAIGNS(CAMPAIGN_ID),
    BRIEF_TITLE VARCHAR(300) NOT NULL,
    BRIEF_DATE DATE,
    BRIEF_CONTENT VARCHAR(16777216),  -- Full text content of brief
    BRAND_NAME VARCHAR(200),
    PROJECT_TYPE VARCHAR(100),  -- TV, DIGITAL, SOCIAL, INTEGRATED, OOH
    CAMPAIGN_OBJECTIVE VARCHAR(200),
    TARGET_AUDIENCE VARCHAR(500),
    KEY_MESSAGE VARCHAR(1000),
    MANDATORY_ELEMENTS VARCHAR(1000),
    COMPETITIVE_CONTEXT VARCHAR(2000),
    SUCCESS_METRICS VARCHAR(1000),
    TIMELINE VARCHAR(500),
    BUDGET_GUIDANCE VARCHAR(200),
    CREATED_BY VARCHAR(200),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- CAMPAIGN_REPORTS: Unstructured campaign performance reports
CREATE OR REPLACE TABLE CAMPAIGN_REPORTS (
    REPORT_ID VARCHAR(50) PRIMARY KEY,
    CAMPAIGN_ID VARCHAR(50) NOT NULL REFERENCES CAMPAIGNS(CAMPAIGN_ID),
    REPORT_TITLE VARCHAR(300) NOT NULL,
    REPORT_DATE DATE,
    REPORT_CONTENT VARCHAR(16777216),  -- Full text content of report
    REPORT_TYPE VARCHAR(100),  -- WEEKLY, MONTHLY, QUARTERLY, FINAL, POST_MORTEM
    EXECUTIVE_SUMMARY VARCHAR(5000),
    KEY_INSIGHTS VARCHAR(5000),
    RECOMMENDATIONS VARCHAR(5000),
    PERFORMANCE_VS_BENCHMARK VARCHAR(2000),
    OPTIMIZATION_ACTIONS VARCHAR(2000),
    NEXT_STEPS VARCHAR(2000),
    PREPARED_BY VARCHAR(200),
    STATUS VARCHAR(20) DEFAULT 'FINAL',
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- BRAND_GUIDELINES: Brand standards and guidelines documents
CREATE OR REPLACE TABLE BRAND_GUIDELINES (
    GUIDELINE_ID VARCHAR(50) PRIMARY KEY,
    CLIENT_ID VARCHAR(50) NOT NULL REFERENCES CLIENTS(CLIENT_ID),
    GUIDELINE_TITLE VARCHAR(300) NOT NULL,
    GUIDELINE_VERSION VARCHAR(20),
    EFFECTIVE_DATE DATE,
    GUIDELINE_CONTENT VARCHAR(16777216),  -- Full text content of guidelines
    SECTION_TYPE VARCHAR(100),  -- BRAND_VOICE, VISUAL_IDENTITY, MESSAGING, LEGAL, SOCIAL
    BRAND_VOICE VARCHAR(5000),
    TONE_GUIDELINES VARCHAR(2000),
    COLOR_PALETTE VARCHAR(1000),
    TYPOGRAPHY_GUIDELINES VARCHAR(1000),
    LOGO_USAGE VARCHAR(2000),
    DO_DONT_GUIDELINES VARCHAR(5000),
    LEGAL_DISCLAIMERS VARCHAR(2000),
    APPROVAL_REQUIREMENTS VARCHAR(1000),
    CONTACT_INFO VARCHAR(500),
    STATUS VARCHAR(20) DEFAULT 'CURRENT',  -- CURRENT, ARCHIVED, DRAFT
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- ENABLE CHANGE TRACKING FOR CORTEX SEARCH TABLES
-- ============================================================================

ALTER TABLE CREATIVE_BRIEFS SET CHANGE_TRACKING = TRUE;
ALTER TABLE CAMPAIGN_REPORTS SET CHANGE_TRACKING = TRUE;
ALTER TABLE BRAND_GUIDELINES SET CHANGE_TRACKING = TRUE;

-- ============================================================================
-- VERIFICATION
-- ============================================================================

SHOW TABLES IN SCHEMA INNOCEAN_INTELLIGENCE.RAW;

/*
=============================================================================
TABLE CREATION COMPLETE
Total Tables: 19
- Core Tables: CLIENTS, CAMPAIGNS, CREATIVE_ASSETS, MEDIA_PLACEMENTS, MEDIA_PERFORMANCE
- Resource Tables: EMPLOYEES, PROJECTS, TIMESHEETS
- Financial Tables: INVOICES, INVOICE_LINE_ITEMS
- Vendor Tables: VENDORS, VENDOR_CONTRACTS, TALENT, TALENT_USAGE
- Audience Tables: AUDIENCE_SEGMENTS, CAMPAIGN_AUDIENCES
- Unstructured Tables: CREATIVE_BRIEFS, CAMPAIGN_REPORTS, BRAND_GUIDELINES

Next Step: Run 03_generate_synthetic_data.sql
=============================================================================
*/
